---
services:

  xo:
    image: local/xo:5.99.0
    container_name: xo
    environment:
      - TZ=America/Toronto
    volumes:
      - ./xo-data:/var/lib/xo-server
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    security_opt:
      - apparmor:unconfined
    networks:
      - xo_network
    restart: unless-stopped
    depends_on:
      - xo-redis

  xo-redis:
    image: redis:7.4.0-bookworm
    container_name: xo-redis
    environment:
      - TZ=America/Toronto
    command: redis-server --save 600 10 --loglevel warning
    volumes:
      - ./redis-data:/data
    networks:
      - xo_network

networks:
  xo_network:
    driver: bridge
    name: xo_network