---

services:

  xo:
    image: local/xo:5.93.1
    container_name: xo
    environment:
      - TZ=America/Toronto
    volumes:
      - ./config.toml:/etc/xo-server/config.toml
    networks:
      - xo_network
    restart: unless-stopped
    depends_on:
      - xo-redis

  xo-redis:
    image: redis:7.0.15-bookworm
    container_name: xo-redis
    environment:
      - TZ=America/Toronto
    command: redis-server --save 600 10 --loglevel warning
    volumes:
      - ./redis-data:/data
    networks:
      - xo_network

networks:
  xo_network:
    driver: bridge
    name: xo_network
